config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  root to: 'blogs#top'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  resources :blogs do
    collection do
      post :confirm
    end
  end

  resources :favorites, only: [:create, :destroy]

mount LetterOpenerWeb::Engine, at: "/letter_opener"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :image, ImageUploader
    validates :title, presence: true
    validates :content, length: {in: 1..140}
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :icon, IconUploader
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 255},   format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }

  has_secure_password
  validates :password, presence: true, length: {minimum: 6}
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :logged_in?

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?, only: [:new, :edit, :show, :destroy]

  def top
  end

  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if @blog.save
      ContactMailer.contact_mail(@blog).deliver
      redirect_to blogs_path, notice: 'ブログを作成し確認メールを送信しました'
    else
      render 'new'
    end
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
    unless @blog.user_id == current_user.id
      redirect_to blogs_path, notice: "権限がありません"
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: 'ブログを編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: 'ブログを削除しました'
  end

  def confirm
    @user = User.find(session[:user_id])
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    render :new if @blog.invalid?
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content, :image, :image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def logged_in?
    unless current_user.present?
      flash[:notice] = 'ログインしてください'
      redirect_to new_session_path
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:show, :edit, :new, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @favoreites_blogs = @user.favorites
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: 'ブログを編集しました'
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon, :icon_cache)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
      elsif action_name == 'edit'
      blog_path
    end
  end

  end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
     current_user.present?
  end

end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
      elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-xs-12">
      <%= form_with(model: @blog, local: true, url: choose_new_or_edit) do |form| %>
      <% if @blog.errors.any? %>
        <div id="error_explanation">
          <h2><%= @blog.errors.count %>件のエラーがあります</h2>
          <ul>
            <% @blog.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="blog_title">
        <%= form.label :title %>
        <%= form.text_field :title %>
      </div>
      <div class="blog_title">
        <%= form.label :content %>
        <%= form.text_field :content %>
      </div>
      <div class="field">
        <%= form.label :image %>
        <%= image_tag(@blog.image.url) if @blog.image.url %>
        <%= form.file_field :image %>
        <%= form.hidden_field :image_cache %>
        </div>
      <%= form.submit "投稿", class:'botton'%>
    <% end %>
    <%= link_to "ブログ詳細画面に戻る", blogs_path, class:'back_blog' %>
  </div>
</div>
</div>

app/views/blogs/confirm.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-xs-12">
      <h3>以下の内容で送信しますか</h3>
      <%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
      <%= form.hidden_field :title %>
      <%= form.hidden_field :content %>
      <%= image_tag(@blog.image.url, class: 'img-responsive center-block') if @blog.image.url %>
      <%= form.hidden_field :image_cache %>
      <p>投稿者:<%= @user.name %></p>
      <p>タイトル: <%= @blog.title %></p>
      <p>本文:<%= @blog.content %></p>
      <%= form.submit "登録する", class:'botton' %>
    <% end %>

    <%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
    <%= form.hidden_field :title %>
    <%= form.hidden_field :image_cache %>
    <%= form.hidden_field :content %>
    <%= form.submit "戻る", name: 'back', class:'botton' %>
  <% end %>
</div>
</div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-xs-12">
      <h1>ブログを編集する</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="text-center">
  <h1>ブログ一覧</h1>
  <p><%= notice %></p>
  <div class="container">
    <div class="row">
      <% @blogs.each do |blog| %>
        <div class="col-xs-12 col-md-6">

          <p>投稿者:<%= blog.user.name %></p>
          <p>タイトル：<%= blog.title %></p>
          <p>内容：<%= blog.content %></p>
          <p>
            <%= image_tag blog.image, :class =>'img-responsive center-block' %>
            </p>


          <span><%= link_to '詳細', blog_path(blog.id), class:'btn outline btn-primary' %></span>

          <% if logged_in? %>
            <% if blog.user_id == current_user.id %>
              <span><%= link_to '編集', edit_blog_path(blog.id), data: {confirm: '本当に編集しますか？'}, class: 'btn outline btn-info' %></span>
              <span><%= link_to '削除', blog_path(blog.id),method: :delete, data: {confirm: '本当に削除しますか？'}, class:'btn outline btn-dander' %></span>

            <% end %>
          <% end %>

        </div>
      <% end %>
    </div>
  </div>
  <br>
  <%= link_to '新しくブログを作成する', new_blog_path, class:'new_blog' %>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-xs-12">
      <h1>ブログを作成する</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-xs-12">
      <h1>ブログ詳細画面</h1>
      <p>タイトル:<%= @blog.title %></p>
      <p>
        画像:<%= image_tag @blog.image, :class =>'img-responsive center-block' %>
        </p>
      <p>内容:<%= @blog.content %></p>

      <% unless @blog.user_id == current_user.id %>
        <% if @favorite.present? %>
          <%= link_to 'お気に入りを削除する', favorite_path(id: @favorite.id), method: :delete, class:'tn outline btn-primary' %>
        <% else %>
          <%= link_to 'お気に入り', favorites_path(blog_id: @blog.id), method: :post, class:'btn outline btn-info' %>
        <% end %>
      <% end %>
      <br>

      <%= link_to "ブログ一覧画面に戻る", blogs_path, class:'back_show' %>
    </div>
  </div>
</div>

app/views/blogs/top.html.erb
<div class="content">
  <div class="row">
    <div class="col-md-6 col-xs-12">
      <h1>topページ</h1>
      <p>このアプリはブログ機能作成課題で作ったブログアプリにBootstrapで装飾したものです。</p>
      <p>ブログを作成したり、過去のブログを見たりする事ができます。</p>
    </div>
  </div>
</div>
<%= image_tag 'top_blog.jpg', class: 'top_image'%>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :contact_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogapp</title>
    <%= csrf_meta_tags %>
    <meta name="vewport" content="width=device-width">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <header class="header">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-xs-12">
            <nav class="menu">
              <ul class="top_menu clearfix">
                <li>
                  <a><%= link_to "topへ", root_path %></a>
                </li>

                <% if logged_in? %>
                <li>
                  <a><%= link_to "マイページ", user_path(current_user.id) %></a>
                  </li>
                  <li>
                    <a><%= link_to "ブログ一覧", blogs_path %></a>
                  </li>
                  <li>
                    <a><%= link_to '投稿画面へ', new_blog_path %></a>
                  </li>
                  <li>
                    <a><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></a>
                  </li>
                <% else %>
                  <li>
                    <a><%= link_to "登録", new_user_path %></a>
                  </li>
                  <li>
                    <a><%= link_to "ログイン", new_session_path %></a>
                  </li>
                <% end %>
              </ul>
            </nav>
          </div>
        </div>
      </div>

    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>

    <footer class="footer">
      <p>task_blogapp</p>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true, url:choose_new_or_edit) do |form| %>

  <div class="filed">
    <%= form.label :icon %>
    <%= image_tag(@user.icon.url) if @user.icon.url %>
    <%= form.file_field :icon %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to "もどる", user_path %>

app/views/users/new.html.erb
<h1>登録</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %>
      prohibited this @user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
<div class="sin_up">
  <%= f.label :名前 %>
  <%= f.text_field :name %>
</div>
<div class="sin_up">
  <%= f.label :メールアドレス %>
  <%= f.email_field :email %>
</div>
<div class="sin_up">
  <%= f.label :パスワード %>
  <%= f.password_field :password %>
</div>
<div class="sin_up">
  <%= f.label :同じパスワードを入力 %>
  <%= f.password_field :password_confirmation %>
</div>
<div class = "filed">
  <%= f.label :icon %>
    <%= image_tag(@user.icon.url, class: 'icon') if @user.icon.url %>
    <%= f.file_field :icon %>
  </div>
<%= f.submit "Create my acount", class: 'botton' %>
<% end %>

app/views/users/show.html.erb
<div class="container">
<%= image_tag @user.icon, :class => "icon" %>
<h1><%= @user.name %>のブログ</h1>
<p><%= notice %></p>
<h3>お気に入りしたブログ</h3>
<table>
  <% @user.favorite_blogs.each do |blog| %>
  <tr>
    <th>投稿者:<%= blog.user.name %></th>
    <th>タイトル:<%= blog.title %></th>
    <th>内容:<%= blog.content %></th>
    <th>
      <%= image_tag blog.image, :class =>'img-responsive center-block' %>
      </th>
    </tr>
    <% end %>
    </table>
</div>